### ISSUE TITLE
Preserve (comma) separator characters

### ISSUE THREAD

**Issue by stkb** [henriiik/vscode-sort#1]
Hi, thanks for the great plugin!

Something I'd like to be able to do with it though, is sort a list of comma-separated variable names. Eg:

```
CompletionItem, Range, Position
```

Would get sorted to:

```
CompletionItem, Position, Range
```

(Instead it currently gets sorted to:)

```
CompletionItem, Position Range,
```

I can work on it myself if you don't have time (and are happy with adding the feature)

**Comment by henriiik** [comment]
Hello!

I'm glad you like the plugin!

I have had a look and I've got an idea how i could implement the feature. I'll try and get it done this weekend. :)

**Comment by henriiik** [comment]
Hello!

I just published a new version to the marketplace, that can handle comma-separated words and lines.

Please let me know if you find any bugs. :)

**Comment by stkb** [comment]
Thanks! it's nearly there, but I'd really like it to work with surrounding whitespace too. :) 

`c, a, b` now sorts to `a, b, c`, but `␣c, a, b␣` (␣ represents a space on each end) sorts to `␣␣a, b c,`

I just realised surrounding whitespace is something it didn't preserve yet anyway:

`␣c a b␣` sorts to `␣␣a b c` (2 spaces in front).
`␣a b c␣` also sorts to `␣␣a b c`

**Comment by henriiik** [comment]
That seemed like a reasonable request, so i added it.

And published a new version. :)

**Comment by stkb** [comment]
Perfect! Thanks!
