### ISSUE TITLE
Extraneous text in final line of line sort

### ISSUE THREAD

**Issue by cliffkoh** [henriiik/vscode-sort#2]
```
ISiteHeaderProps,
ISiteLogoInfo,
IHorizontalNavProps,
IHorizontalNavItem,
CompositeHeader,
ICompositeHeaderProps,
IGoToOutlookProps
```

Result: (notice the extra IGoToOutlookProps in the last line...)

```
CompositeHeader,
ICompositeHeaderProps,
IGoToOutlookProps,
IHorizontalNavItem,
IHorizontalNavProps,
ISiteHeaderProps,
ISiteLogoInfoIGoToOutlookProps
```

**Comment by henriiik** [comment]
Hello!

Thank you for your bug-rapport! I have fixed the issue and published a new version of the extension.

There seems to have been a change in how Code handles creation of positions at the end of a line which caused this issue.

**Comment by cliffkoh** [comment]
Thank you :) And thank you for the extension!

**Comment by henriiik** [comment]
I'm glad you like it! :)
